blank_issues_enabled: false
# contact_links:
#   - name: 💬 Community Discussions
#     url: https://github.com/arthvm/project/discussions
#     about: For general questions and community discussions
#
#   - name: 🔒 Critical Security Issues
#     url: mailto:arthvm@proton.me
#     about: Report critical vulnerabilities privately
#
#   - name: 📖 Documentation
#     url: https://docs.example.com
#     about: Check our official documentation
#
#   - name: 💭 Feature Discussions
#     url: https://github.com/username/project/discussions/categories/ideas
#     about: Discuss feature ideas with the community before creating requests
