name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "feature"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the feature you'd like to see
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: problem_motivation
    attributes:
      label: Problem/Motivation
      description: What problem would this feature solve? Why is it needed?
      placeholder: Currently, when I try to..., I have to... which is inefficient because...
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed solution
      description: How do you envision this feature working?
      placeholder: The feature could work by...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: What should happen when this feature is implemented?
      placeholder: When I use this feature, it should...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried..., but it doesn't work because...

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Any other information, mockups, or examples that would help
      placeholder: Here's a mockup of how it could look...
