name: ❓ Question
description: Ask a question about the project
title: "[QUESTION] "
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Before asking:**
        - ✅ I've checked the documentation
        - ✅ I've searched existing issues
        - ✅ I've looked at the FAQ/Wiki

        Please provide details about your question below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to know?
      placeholder: I'm trying to understand how to...
    validations:
      required: true

  - type: textarea
    id: what_tried
    attributes:
      label: What I've tried
      description: What approaches or solutions have you already attempted?
      placeholder: |
        1. I tried following the docs at...
        2. I attempted to use...
        3. I looked at similar issues...
    validations:
      required: true

  - type: textarea
    id: expected_outcome
    attributes:
      label: Expected outcome
      description: What result are you hoping to achieve?
      placeholder: I expect to be able to...

  - type: textarea
    id: current_behavior
    attributes:
      label: Current behavior
      description: What's happening instead? Include any error messages
      placeholder: Currently, when I..., it shows...

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Relevant system information
      placeholder: |
        * Version: v1.2.3
        * OS: Ubuntu 22.04
        * Configuration: default/custom
      render: markdown

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Any other information that might be relevant
      placeholder: I'm working on a project where...
